dependencies:
- name: drg-bets
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.119
- name: drg-landing-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
